// src/components/login-form.tsx
import { cn } from '@/lib/utils';
import { Button } from '@/components/ui/button';
import {
    Card,
    CardContent,
    CardDescription,
    CardHeader,
    CardTitle,
} from '@/components/ui/card';
// import { Input } from "@/components/ui/input"
// import { Label } from "@/components/ui/label"
import { User } from 'lucide-react';
import { Link } from 'react-router';
import DiscordLogo from '@/assets/DiscordLogo';
import GoogleLogo from '@/assets/GoogleLogo';

export function LoginForm({
    className,
    ...props
}: React.ComponentProps<'div'>) {
    return (
        <div className={cn('flex flex-col gap-6', className)} {...props}>
            <Card className="bg-zinc-500/40 backdrop-blur backdrop-opacity-55">
                <CardHeader className="text-center">
                    <CardTitle className="text-xl">Welcome back</CardTitle>
                    <CardDescription className="text-accent-foreground">
                        Login with your Discord or Google account
                    </CardDescription>
                </CardHeader>
                <CardContent>
                    <form>
                        <div className="grid gap-6">
                            <div className="flex flex-col gap-4">
                                <Link
                                    to="/"
                                    className="bg-zinc-500/50 rounded-md"
                                >
                                    <Button
                                        variant="outline"
                                        className="w-full border-2 hover:border-5"
                                    >
                                        <DiscordLogo className="size-5 stroke-0" />
                                        Login with Discord
                                    </Button>
                                </Link>
                                <Link
                                    to="/"
                                    className="bg-zinc-500/50 rounded-md"
                                >
                                    <Button
                                        variant="outline"
                                        className="w-full border-2 hover:border-5"
                                    >
                                        <GoogleLogo />
                                        Login with Google
                                    </Button>
                                </Link>
                                <Link
                                    to="/"
                                    className="bg-zinc-500/50 rounded-md"
                                >
                                    <Button
                                        variant="outline"
                                        className="w-full border-2 hover:border-5"
                                    >
                                        <User className="size-5" />
                                        Continue as Guest
                                    </Button>
                                </Link>
                            </div>
                            {/* <div className="after:border-border relative text-center text-sm after:absolute after:inset-0 after:top-1/2 after:z-0 after:flex after:items-center after:border-t">
                <span className="bg-card text-muted-foreground relative z-10 px-2">
                  Or continue with
                </span>
              </div>
              <div className="grid gap-6">
                <div className="grid gap-3">
                  <Label htmlFor="email">Email</Label>
                  <Input
                    id="email"
                    type="email"
                    placeholder="m@example.com"
                    required
                  />
                </div>
                <div className="grid gap-3">
                  <div className="flex items-center">
                    <Label htmlFor="password">Password</Label>
                    <a
                      href="#"
                      className="ml-auto text-sm underline-offset-4 hover:underline"
                    >
                      Forgot your password?
                    </a>
                  </div>
                  <Input id="password" type="password" required />
                </div>
                <Button type="submit" className="w-full">
                  Login
                </Button>
              </div>
              <div className="text-center text-sm">
                Don&apos;t have an account?{" "}
                <a href="#" className="underline underline-offset-4">
                  Sign up
                </a>
              </div> */}
                        </div>
                    </form>
                    <div className="text-accent-foreground/60 mt-7 *:[a]:hover:text-primary text-center text-xs text-balance *:[a]:underline *:[a]:underline-offset-4">
                        By continuing, you agree to our{' '}
                        <a href="#">Terms of Service</a> and{' '}
                        <a href="#">Privacy Policy</a>.
                    </div>
                </CardContent>
            </Card>
        </div>
    );
}

// src/components/layout/Login/LoginForm.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import { cn } from '@/lib/utils'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Icon } from '@iconify/vue'

const props = defineProps<{
  class?: HTMLAttributes['class']
}>()
</script>

<template>
  <form :class="cn('flex flex-col gap-6', props.class)">
    <div class="flex flex-col items-center gap-2 text-center">
      <h1 class="text-2xl font-bold">
        Welcome Back
      </h1>
      <p class="text-muted-foreground text-sm text-balance">
        Enter your email below to login to your account
      </p>
    </div>
    <div class="grid gap-6">
      <div class="grid gap-3">
        <Label for="email">Email</Label>
        <Input id="email" type="email" placeholder="goku@animepack.net" required />
      </div>
      <div class="grid gap-3">
        <div class="flex items-center">
          <Label for="password">Password</Label>
          <a href="#" class="ml-auto text-sm underline-offset-4 hover:underline">
            Forgot your password?
          </a>
        </div>
        <Input id="password" type="password" required />
      </div>
      <Button type="submit" class-name="w-full">
        Login
      </Button>
    </div>
  </form>
  <div
    class="after:border-border my-3 relative text-center text-sm after:absolute after:inset-0 after:top-1/2 after:z-0 after:flex after:items-center after:border-t">
    <span class="bg-background/50 rounded-md text-muted-foreground relative z-10 px-2">
      Or continue with
    </span>
  </div>
  <div class="flex flex-col gap-3">
    <Button variant="outline" class-name="w-full">
      <span class="flex flex-row gap-3">
        <Icon icon="fa6-brands:discord" class="size-5.5" />
        Login with Discord
      </span>
    </Button>
    <Button variant="outline" class-name="w-full">
      <span class="flex flex-row gap-3">
        <Icon icon="fa6-brands:google" class="size-5" />
        Login with Google
      </span>
    </Button>
    <div class="text-center text-sm">
      Don't have an account?
      <a href="#" @click="$emit('toggleSignup')" class="underline underline-offset-4">
        Sign up
      </a>
    </div>
  </div>
</template>
